# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: community
name: molecule
version: 0.2.0
readme: README.md
authors:
  - Sorin Sbarnea (github/ssbarnea)
description: Ansible Molecule collection contains molecule specific plugins.
license: MIT
tags:
  - molecule
  - testing
repository: https://github.com/ansible-collections/community.molecule
homepage: https://github.com/ansible-collections/community.molecule
issues: https://github.com/ansible-collections/community.molecule/issues
build_ignore:
  - .gitignore
  - .github
  - changelogs/.plugin-cache.yaml
  - Makefile
